mindmap
  root((Use Cases))
    inventory
      CreateInventory
      ApplyPromotionToSale
      RemovePromotionFromSale
      UpdateProductSaleInventory
    store
      CreateStore
      ToggleBulkSale
      ToggleCommission
      UpdateStoreContact
    promotion
      CreatePromotion
      ActivatePromotion
      DeactivatePromotion
    reference_price
      CreateReferencePrice
    sales_commission
      CreateSalesCommission
      UpdateMaxPrice
      UpdateMinQty
    store_allowed_category
      CreateCategory
      ApproveCategory
      RejectCategory
    store_warehouse_link
      CreateLink
      ChangeRelation
    warehouse
      CreateWarehouse
      UpdateVisibility
      UpdateContact
